INFO:     Will watch for changes in these directories: ['/home/rino/deploy/backend']
INFO:     Uvicorn running on http://0.0.0.0:8010 (Press CTRL+C to quit)
INFO:     Started reloader process [1282563] using StatReload
INFO:     Started server process [1282572]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
[{'type': 'connexion', 'name': 'postgres/Employee', 'description': 'Pour r√©cup√©rer les informations sur les employ√©s'}]
üîé Sources s√©lectionn√©es : [{'type': 'connexion', 'name': 'postgres/Employee'}]
Table : Employee
Colonnes :
- EmployeeId (integer, NOT NULL)
- LastName (character varying, NOT NULL)
- FirstName (character varying, NOT NULL)
- Title (character varying, NULLABLE)
- ReportsTo (integer, NULLABLE)
- BirthDate (timestamp without time zone, NULLABLE)
- HireDate (timestamp without time zone, NULLABLE)
- Address (character varying, NULLABLE)
- City (character varying, NULLABLE)
- State (character varying, NULLABLE)
- Country (character varying, NULLABLE)
- PostalCode (character varying, NULLABLE)
- Phone (character varying, NULLABLE)
- Fax (character varying, NULLABLE)
- Email (character varying, NULLABLE)
Assistant : Bonjour, comment puis-je vous assister aujourd'hui ? N'h√©sitez pas √† poser votre question.
Utilisateur : avons nous effectuez de recrutement en Mars?
Assistant : Oui, il y a eu une op√©ration de recrutement en mars.
extracted sql: SELECT "FirstName", "LastName", "Title", "Phone", "Email", "Address"
[Erreur ex√©cution SQL via API] : 500 Server Error: Internal Server Error for url: https://postgresvectorizer.onirtech.com/execute
INFO:     129.222.109.139:0 - "POST /ask HTTP/1.0" 200 OK
[{'type': 'connexion', 'name': 'postgres/Employee', 'description': 'Pour r√©cup√©rer les informations sur les employ√©s'}]
üîé Sources s√©lectionn√©es : [{'type': 'connexion', 'name': 'postgres/Employee'}]
Table : Employee
Colonnes :
- EmployeeId (integer, NOT NULL)
- LastName (character varying, NOT NULL)
- FirstName (character varying, NOT NULL)
- Title (character varying, NULLABLE)
- ReportsTo (integer, NULLABLE)
- BirthDate (timestamp without time zone, NULLABLE)
- HireDate (timestamp without time zone, NULLABLE)
- Address (character varying, NULLABLE)
- City (character varying, NULLABLE)
- State (character varying, NULLABLE)
- Country (character varying, NULLABLE)
- PostalCode (character varying, NULLABLE)
- Phone (character varying, NULLABLE)
- Fax (character varying, NULLABLE)
- Email (character varying, NULLABLE)
Assistant : Bonjour, comment puis-je vous assister aujourd'hui ? N'h√©sitez pas √† poser votre question.
Utilisateur : avons nous effectuez de recrutement en Mars?
Assistant : Oui, il y a eu une op√©ration de recrutement en mars.
extracted sql: SELECT "FirstName", "LastName"
[Erreur ex√©cution SQL via API] : 500 Server Error: Internal Server Error for url: https://postgresvectorizer.onirtech.com/execute
INFO:     129.222.109.139:0 - "POST /ask HTTP/1.0" 200 OK
[{'type': 'connexion', 'name': 'postgres/Employee', 'description': 'Pour r√©cup√©rer les informations sur les employ√©s'}]
üîé Sources s√©lectionn√©es : [{'type': 'connexion', 'name': 'postgres/Employee'}]
INFO:     129.222.109.139:0 - "POST /ask HTTP/1.0" 200 OK
INFO:     34.48.104.241:0 - "GET / HTTP/1.0" 404 Not Found
INFO:     82.102.18.180:0 - "GET / HTTP/1.0" 404 Not Found
INFO:     82.102.18.180:0 - "GET //wp-includes/wlwmanifest.xml HTTP/1.0" 404 Not Found
INFO:     82.102.18.180:0 - "GET //xmlrpc.php?rsd HTTP/1.0" 404 Not Found
INFO:     82.102.18.180:0 - "GET / HTTP/1.0" 404 Not Found
INFO:     82.102.18.180:0 - "GET //blog/wp-includes/wlwmanifest.xml HTTP/1.0" 404 Not Found
INFO:     82.102.18.180:0 - "GET //web/wp-includes/wlwmanifest.xml HTTP/1.0" 404 Not Found
INFO:     82.102.18.180:0 - "GET //wordpress/wp-includes/wlwmanifest.xml HTTP/1.0" 404 Not Found
INFO:     82.102.18.180:0 - "GET //website/wp-includes/wlwmanifest.xml HTTP/1.0" 404 Not Found
INFO:     82.102.18.180:0 - "GET //wp/wp-includes/wlwmanifest.xml HTTP/1.0" 404 Not Found
INFO:     82.102.18.180:0 - "GET //news/wp-includes/wlwmanifest.xml HTTP/1.0" 404 Not Found
INFO:     82.102.18.180:0 - "GET //2018/wp-includes/wlwmanifest.xml HTTP/1.0" 404 Not Found
INFO:     82.102.18.180:0 - "GET //2019/wp-includes/wlwmanifest.xml HTTP/1.0" 404 Not Found
INFO:     82.102.18.180:0 - "GET //shop/wp-includes/wlwmanifest.xml HTTP/1.0" 404 Not Found
INFO:     82.102.18.180:0 - "GET //wp1/wp-includes/wlwmanifest.xml HTTP/1.0" 404 Not Found
INFO:     82.102.18.180:0 - "GET //test/wp-includes/wlwmanifest.xml HTTP/1.0" 404 Not Found
INFO:     82.102.18.180:0 - "GET //media/wp-includes/wlwmanifest.xml HTTP/1.0" 404 Not Found
INFO:     82.102.18.180:0 - "GET //wp2/wp-includes/wlwmanifest.xml HTTP/1.0" 404 Not Found
INFO:     82.102.18.180:0 - "GET //site/wp-includes/wlwmanifest.xml HTTP/1.0" 404 Not Found
INFO:     82.102.18.180:0 - "GET //cms/wp-includes/wlwmanifest.xml HTTP/1.0" 404 Not Found
INFO:     82.102.18.180:0 - "GET //sito/wp-includes/wlwmanifest.xml HTTP/1.0" 404 Not Found
WARNING:  StatReload detected changes in 'rag/rag_engine.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [1282572]
INFO:     Started server process [1352984]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected changes in 'rag/rag_engine.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [1352984]
INFO:     Started server process [1353030]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected changes in 'rag/rag_engine.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [1353030]
INFO:     Started server process [1353057]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected changes in 'main.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [1353057]
INFO:     Started server process [1353106]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  StatReload detected changes in 'main.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [1353106]
INFO:     Started server process [1353114]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     102.17.105.208:0 - "OPTIONS /ask HTTP/1.0" 200 OK
[{'type': 'connexion', 'name': 'postgres/Employee', 'description': 'Pour r√©cup√©rer les informations sur les employ√©s'}]
INFO:     102.17.105.208:0 - "POST /ask HTTP/1.0" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/rino/deploy/lib64/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/rino/deploy/lib64/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/home/rino/deploy/lib64/python3.9/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/rino/deploy/lib64/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/rino/deploy/lib64/python3.9/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/home/rino/deploy/lib64/python3.9/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/home/rino/deploy/lib64/python3.9/site-packages/starlette/middleware/cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/rino/deploy/lib64/python3.9/site-packages/starlette/middleware/cors.py", line 144, in simple_response
    await self.app(scope, receive, send)
  File "/home/rino/deploy/lib64/python3.9/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/rino/deploy/lib64/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/rino/deploy/lib64/python3.9/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/rino/deploy/lib64/python3.9/site-packages/starlette/routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/rino/deploy/lib64/python3.9/site-packages/starlette/routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "/home/rino/deploy/lib64/python3.9/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/rino/deploy/lib64/python3.9/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/rino/deploy/lib64/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/rino/deploy/lib64/python3.9/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/rino/deploy/lib64/python3.9/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/home/rino/deploy/lib64/python3.9/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/home/rino/deploy/lib64/python3.9/site-packages/fastapi/routing.py", line 214, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/rino/deploy/lib64/python3.9/site-packages/starlette/concurrency.py", line 37, in run_in_threadpool
    return await anyio.to_thread.run_sync(func)
  File "/home/rino/deploy/lib64/python3.9/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/rino/deploy/lib64/python3.9/site-packages/anyio/_backends/_asyncio.py", line 2470, in run_sync_in_worker_thread
    return await future
  File "/home/rino/deploy/lib64/python3.9/site-packages/anyio/_backends/_asyncio.py", line 967, in run
    result = context.run(func, *args)
  File "/home/rino/deploy/backend/main.py", line 180, in ask_question
    relevant_sources = ask_mixtral_for_relevant_sources(req.chatbot_id, req.question)
  File "/home/rino/deploy/backend/main.py", line 161, in ask_mixtral_for_relevant_sources
    response.raise_for_status()
  File "/home/rino/deploy/lib64/python3.9/site-packages/requests/models.py", line 1026, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Content for url: https://api.infomaniak.com/1/ai/105104/openai/chat/completions
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [1353114]
INFO:     Stopping reloader process [1282563]
